using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using TMPro.EditorUtilities;
using Unity.VisualScripting;

public class Healkit : MonoBehaviour
{
    // UI Test Чв АХ
    public Image backGround;
    public TMP_Text title;

    public Image backGround2;
    public TMP_Text explanation;

    public Image backGround3;
    public TMP_Text pickUp;

    public Player player;
    public Vector3 UIPosition;

    // МГИэ УЂРЬ ЖчПіСјДй.
    bool isSetting;
    // ОЦРЬХлРЬ ИдОюСГРИИщ НЧЧрЧбДй.
    bool isPickup;

    void Start()
    {
        Initalize();
    }

    /// АХИЎ КёЗЪЗЮ ХЉБтАЁ СйОњДй ФПСГДй ЧиОпЕЩ АХ ААОЦ.
    private void Update()
    {
        if (player.IsTargetVisible(transform))
        {
            if (player.IsRayTarget(transform))
            {
                title.text = "БИБо ЛѓРк";
                title.transform.position = Camera.main.WorldToScreenPoint(transform.position + UIPosition);
                backGround.transform.position = Camera.main.WorldToScreenPoint(transform.position + UIPosition);
                backGround.color = new Color(0.0f, 0.0f, 0.0f, 0.5f);

                if (isSetting)
                {
                    explanation.text = "УМЗТРЛ 10 ШИКЙЧеДЯДй.";
                    explanation.transform.position = Camera.main.WorldToScreenPoint(transform.position - UIPosition);
                    backGround2.transform.position = Camera.main.WorldToScreenPoint(transform.position - UIPosition);
                    backGround2.color = new Color(0.0f, 0.0f, 0.0f, 0.5f);
                    explanation.color = new Color(1.0f, 1.0f, 1.0f, 0.5f);
                }
                else
                {
                    explanation.text = "";
                    backGround2.color = new Color(0.0f, 0.0f, 0.0f, 0.0f);
                }
            }
            else
            {
                title.text = "";
                backGround.color = new Color(0.0f, 0.0f, 0.0f, 0.0f);
            }
        }
        else
        {
            title.text = "";
            backGround.color = new Color(0.0f, 0.0f, 0.0f, 0.0f);
        }
    }

    private void OnCollisionEnter(Collision collision)
    {
        // 7РК ПЉБтМ­ PlayerДй.
        if(collision.gameObject.layer == 7)
        {
            // ДъОвРИИщ ЙКАЁ ЧиОп ЧЯДТЕЅ ??
            // ОЦРЬХлРЬ ИдРК АХДЯБю
            gameObject.SetActive(false);
            isPickup = true;
            // ИдОњРЛ ЖЇ ГЊПРДТ UI
            backGround3.color = new Color(0.0f, 0.0f, 0.0f, 0.5f);
            pickUp.color = new Color(1.0f, 0.0f, 0.0f, 1.0f);
            pickUp.text = "УМЗТРЛ 10 ШИКЙЧеДЯДй.";
            Invoke("DestoryText", 3.0f);
        }
    }

    // УЪБтФЁ
    private void Initalize()
    {
        backGround.color = new Color(0.0f, 0.0f, 0.0f, 0.0f);
        backGround2.color = new Color(0.0f, 0.0f, 0.0f, 0.0f);
        backGround3.color = new Color(0.0f, 0.0f, 0.0f, 0.0f);
        
        title.text = "";
        title.fontSize = 18;
        explanation.fontSize = 10;
        pickUp.fontSize = 10;

        title.color = new Color(1.0f, 1.0f, 1.0f, 0.5f);
        title.alignment = TextAlignmentOptions.Center;
        explanation.alignment = TextAlignmentOptions.Center;
        pickUp.alignment = TextAlignmentOptions.Center;
        UIPosition.y = 0.3f;
    }

    // item objectПЁДйАЁ РЬАЭРЛ ГжРЛ АЭРЬДй.
    private void OnMouseEnter()
    {
        isSetting = true;
    }

    private void OnMouseExit()
    {
        isSetting = false;
    }

    void DestoryText()
    {
        backGround3.color = new Color(0.0f, 0.0f, 0.0f, 0.0f);
        pickUp.color = new Color(1.0f, 0.0f, 0.0f, 0.0f);
        pickUp.text = "";
    }
}
